server:
  port: 18090
  servlet:
    context-path: /
  error:
    include-stacktrace: never

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      # deals with single and multi-valued JWT claims
      accept-single-value-as-array: true
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: 'http://localhost:3000/oauth/v2/introspect'
          client-id: '286769127262060547'
          client-secret: 'JXpAKwbebjQrpwHGjn4inp1aodheqvIdCDrR8A8L1Ask5eSZK66GKbCXqOgomHOZ'

logging:
  level:
    root: info
    demo: debug
    org:
      springframework:
        web: info
        security: debug